# Generated by Django 4.0.4 on 2022-05-25 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_user'),
        ('luggage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggage',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip'),
        ),
    ]
