# Generated by Django 4.0.4 on 2022-05-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0002_stop_day_alter_stop_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
