# Generated by Django 4.0.4 on 2022-05-26 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0003_stop_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='name',
        ),
    ]
