# Generated by Django 4.0.4 on 2022-05-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0004_remove_stop_description_remove_stop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='longitude',
        ),
        migrations.AddField(
            model_name='stop',
            name='lat',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop',
            name='lng',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
