# Generated by Django 4.0.4 on 2022-05-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0005_remove_stop_latitude_remove_stop_longitude_stop_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stop',
            name='lng',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
    ]
