# Generated by Django 4.0.4 on 2022-05-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0007_alter_stop_lat_alter_stop_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='stop',
            name='lng',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
