# Generated by Django 4.0.4 on 2022-05-31 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0008_alter_stop_lat_alter_stop_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop',
            old_name='day',
            new_name='stop_number',
        ),
    ]
